version: '3'
services:
    web-service:
        build: ./webService
        ports:
            - 80:80
    
    retrieve-all-service:
        build: ./retrieveAllService
        ports:
            - 8081:80
    
    search-service:
        build: ./searchService
        ports:
            - 8082:80
                
    nginx: 
        image: nginx:latest
        container_name: interesting_kare
        volumes:
          - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
          - 8083:80